btl_web/Controllers/SinhvienController.cs
using Framework.EF;
using Framework.Model;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace btl_web.Controllers
{
    public class SinhvienController : Controller
    {
        private readonly Model1 db = new Model1();
        // GET: Sinhvien
        public ActionResult SinhvienIndex()
        {
            return View();
        }
        [HttpGet]
        public ActionResult listSinhvien()
        {
            var listSinhvien = new List<SinhVien>();
            var list = db.SinhViens.ToList();
            foreach (var item in list)
            {
                var model = new SinhVien();
                model.Masinhvien = item.Masinhvien;
                model.Tensinhvien = item.Tensinhvien;
                model.Lop = item.Lop;
                listSinhvien.Add(model);

            }
            return Json(listSinhvien, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveChange(SinhVien model, int id)
        {
            try
            {
                if (id > 0)
                {
                    var update = db.SinhViens.FirstOrDefault(x => x.Masinhvien == model.Masinhvien);
                    update.Tensinhvien = model.Tensinhvien;
                    update.Lop = model.Lop;

                    db.SaveChanges();
                    return Json(new JMessage() { Error = false, Title = "Cap nhat ban ghi thanh cong !" });
                }
                var checkSinhVien = db.SinhViens.FirstOrDefault(x => x.Masinhvien == model.Masinhvien);
                if (checkSinhVien != null)
                {
                    return Json(new JMessage() { Error = true, Title = "Bản ghi đã tồn tại !" });
                }
                db.SinhViens.Add(model);
                db.SaveChanges();
                return Json(new JMessage() { Error = false, Title = "Thêm mới thành công !" });
            }
            catch
            {
                return Json(new JMessage() { Error = true, Title = "Đã cõ lỗi xảy ra trong quá trình thực hiện !" });
            }
        }
        [HttpDelete]
        public JsonResult Delete(string Masinhvien)
        {
            try
            {
                var delete = db.SinhViens.FirstOrDefault(x => x.Masinhvien == Masinhvien);
                if (delete != null)
                {

                    db.SinhViens.Remove(delete);
                    db.SaveChanges();
                    return Json(new JMessage { Error = false, Title = "Xoa thanh cong!" });
                }
                else
                {
                    return Json(new JMessage { Error = true, Title = "Khong tim thay ban ghi!" });
                }
            }
            catch
            {
                return Json(new JMessage { Error = true, Title = "Đã cõ lỗi xảy ra trong quá trình thực hiện!" });
            }
        }
        [HttpPost]
        public JsonResult getInfoId(string Masinhvien)
        {
            if (Masinhvien != null)
            {
                var sach = db.SinhViens.FirstOrDefault(x => x.Masinhvien == Masinhvien);
                return Json(new SinhVien() { Masinhvien = sach.Masinhvien, Tensinhvien = sach.Tensinhvien, Lop = sach.Lop, }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult timkiem(string tuKhoa)
        {
            //Lấy danh sách kho
            IQueryable<SinhVien> lst = db.SinhViens;
            //Nếu có từ khóa cần tìm kiếm


            if (!String.IsNullOrEmpty(tuKhoa))
            {
                lst = lst.Where(p => p.Masinhvien.Contains(tuKhoa) || p.Lop.Contains(tuKhoa) || p.Tensinhvien.Contains(tuKhoa));
            }

            return View(lst.OrderByDescending(p => p.Masinhvien));
        }


        public void ToExcel()
        {
            var listSinhvien = new List<SinhVien>();
            var list = db.SinhViens.ToList();
            foreach (var item in list)
            {
                var model = new SinhVien();
                model.Masinhvien = item.Masinhvien;
                model.Tensinhvien = item.Tensinhvien;
                model.Lop = item.Lop;
                listSinhvien.Add(model);

            }


            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Communication";
            ws.Cells["B1"].Value = "Com2";

            ws.Cells["A2"].Value = "Report";
            ws.Cells["B2"].Value = "Report2";

            ws.Cells["A3"].Value = "Date";
            ws.Cells["B3"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A6"].Value = "Mã sinh viên";
            ws.Cells["B6"].Value = "Tên sinh viên";
            ws.Cells["C6"].Value = "Lớp";


            int rowStart = 7;
            foreach (var item in list)
            {
                if (item.Masinhvien.Count() < 5)
                {
                    ws.Row(rowStart).Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    ws.Row(rowStart).Style.Fill.BackgroundColor.SetColor(ColorTranslator.FromHtml(string.Format("pink")));

                }

                ws.Cells[string.Format("A{0}", rowStart)].Value = item.Masinhvien;
                ws.Cells[string.Format("B{0}", rowStart)].Value = item.Tensinhvien;
                ws.Cells[string.Format("C{0}", rowStart)].Value = item.Lop;

                rowStart++;
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "ExcelReport.xlsx");
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();

        }

    }
}

btl_web/Views/Sinhvien/SinhvienIndex.cshtml
@{
    ViewBag.Title = "SinhvienIndex";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="row text-right">
            <button class="btn btn-info" id="btnadd" data-target="#myModal" data-toggle="modal">Thêm mới</button>
        </div>
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">Tables</a>
                </li>
                <li class="active">Simple &amp; Dynamic</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                @using (Html.BeginForm("timkiem", "SinhVien", FormMethod.Post))
                {
                    <div class="input-group mb-3">
                        @Html.TextBox("tuKhoa", null, new { @class = "form-control", @style = "width : 200px" })
                        <input type="submit" value="Tìm kiếm" style="height:35px" class="btn btn-info" />
                    </div>

                }
            </div><!-- /.nav-search -->
        </div>
        <div class="page-content">
            <!-- PAGE CONTENT BEGINS -->
            <div class="col-sm-12">
                <table id="simple-table" class="table  table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="center">
                                <label class="pos-rel">
                                    <input type="checkbox" class="ace" />
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th>Mã Sinh Viên</th>
                            <th>Tên Sinh Viên</th>
                            <th>Lớp</th>
                            <th>Xử lý</th>
                        </tr>
                    </thead>

                    <tbody id="table"></tbody>
                </table>
            </div><!-- /.span -->
            <div class="col-md-12" style="text-align:right">
                <a href="@Url.Action("ToExcel","SinhVien")" class="btn btn-default"><i class="fa fa-save" aria-hidden="true"></i> Export Excel</a>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="width:75%; margin: 0 auto;">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <i class="fa fa-home"></i>  Thông tin sinh viên
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body validate-form">
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Mã sinh viên</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập mã sinh viên">
                            <input type="text" class="form-control" placeholder="Mã sinh viên" id="txtMaSinhVien" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Tên sinh viên</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập tên sinh viên">
                            <input type="text" class="form-control" placeholder="Tên sinh viên" id="txtTenSinhVien" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Lớp</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập lớp">
                            <input type="text" class="form-control" placeholder="Lớp" id="txtLop" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="name" id="txtId" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Thoát
                </button>
                <button type="button" class="btn btn-info" id="btnsave">Lưu <i class="fa fa-download"></i></button>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="~/Content/alert.css" />
<link rel="stylesheet" href="~/Content/assets/css/font-awesome.min.css" />
@section script{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Content/assets/javacript-admin/Sinhvien.js"></script>
}

btl_web/Views/Sinhvien/timkiem.cshtml
@model IEnumerable<Framework.EF.SinhVien>

@{
    ViewBag.Title = "NXB";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">Tables</a>
                </li>
                <li class="active">Simple &amp; Dynamic</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">

                @using (Html.BeginForm("timkiem", "SinhVien", FormMethod.Post))
                {
                    <div class="input-group mb-3">
                        @Html.TextBox("tuKhoa", null, new { @class = "form-control", @style = "width : 200px" })
                        <input type="submit" value="Tìm kiếm" style="height:35px" class="btn btn-info" />
                    </div>

                }

            </div><!-- /.nav-search -->

        </div>
        <div class="page-content">
            <!-- PAGE CONTENT BEGINS -->
            <div class="container-fluid">
                <div class="col-sm-12">
                    <table id="simple-table" class="table  table-bordered table-hover">
                        <thead>
                            <tr>

                                <th>Mã Sinh Viên</th>
                                <th>Tên Sinh Viên</th>
                                <th>Lớp</th>

                            </tr>

                        </thead>
                        <tbody id="table">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Masinhvien)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Tensinhvien)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Lop)
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!-- /.span -->
                <div class="col-md-12" style="text-align:right">
                    <a href="@Url.Action("SinhvienIndex","Sinhvien")" class="btn btn-success">Back</a>
                </div>
                <!-- PAGE CONTENT ENDS -->
            </div>
        </div>
    </div>
</div>