btl_web/Controllers/LoginController.cs
using Framework.EF;
using Framework.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace btl_web.Controllers
{
    
    public class Account
    {
        public string username { get; set; }
        public string password { get; set; }
        public bool remmember { get; set; }
    }
    public class LoginController : Controller
    {
        private readonly Model1 db = new Model1();
       public ActionResult Index()
        {
            var model = new Account();
            if (Request.Cookies["Account"] != null)
            {
                model.username = Request.Cookies["Account"].Values["UserName"];
                model.password = Request.Cookies["Account"].Values["Password"];
                model.remmember = true;
                return View(model);
            }
            else
            {
                model.remmember = false;
                return View(model);
            }
        }


        public ActionResult Abc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginUserName(Account model)
        {
            var msg = new JMessage();
            try
            {
                if(model != null)
                {
                    var checklogin = db.Users.Where(x => x.UserName.Equals(model.username) && x.Password.Equals(model.password)).FirstOrDefault();
                    if(checklogin == null)
                    {
                        msg.Title = "Sai tai khoan hoac mat khau!";
                        msg.Error = true;
                        return Json(msg, JsonRequestBehavior.AllowGet);
                    }
                    if(checklogin.Status == false)
                    {
                        msg.Title = "Tai khoan da bi khoa";
                        msg.Error = true;
                        return Json(msg, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        if(model.remmember == true)
                        {
                            HttpCookie cookie = new HttpCookie("Account");
                            cookie.Values.Add("UserName", model.username);
                            cookie.Values.Add("Password", model.password);
                            cookie.Expires = DateTime.Now.AddDays(10);
                            Response.Cookies.Add(cookie);
                        }
                        else
                        {
                            Response.Cookies["Account"].Expires = DateTime.Now.AddDays(-30);
                        }
                        msg.Error = false;
                        return Json(msg, JsonRequestBehavior.AllowGet);
                    }

                }
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch
            {
                msg.Error = true;
                msg.Title = "Co loi xay ra trong qua trinh thuc hien!";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

btl_web/Controllers/RegistrationController.cs
using Framework.EF;
using System.Linq;
using System.Web.Mvc;

namespace btl_web.Controllers
{
    public class RegistrationController : Controller
    {
        
        // GET: Registration
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Register()
        {
            User account = new User();

            return View(account);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User account)
        {
            using (Model1 dataprovider = new Model1()) 
            {
                if (dataprovider.Users.Any(x=>x.UserName==account.UserName))
                {
                    ModelState.AddModelError("","Tài Khoản đã tồn tại");
                }
                else if(ModelState.IsValid)
                {
                    dataprovider.Users.Add(account);
                    dataprovider.SaveChanges();
                    ModelState.AddModelError("", account.UserName + " " + "Đăng ký thành công");
                }
            };

            return View();
        }
    }
}

btl_web/Views/Login/Abc.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Abc</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

btl_web/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Login Page - Ace Admin</title>

    <meta name="description" content="User login page" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/assets/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- text fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css" />

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
    <script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.8.10/jquery-ui.min.js"></script>
    <!-- ace styles -->
    <link rel="stylesheet" href="~/Content/assets/css/ace.min.css" />

    <!--[if lte IE 9]>
        <link rel="stylesheet" href="~/Content/assets/css/ace-part2.min.css" />
    <![endif]-->
    <link rel="stylesheet" href="~/Content/assets/css/ace-rtl.min.css" />

    <!--[if lte IE 9]>
      <link rel="stylesheet" href="~/Content/assets/css/ace-ie.min.css" />
    <![endif]-->
    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <!--[if lte IE 8]>
    <script src="~/Content/assets/js/html5shiv.min.js"></script>
    <script src="~/Content/assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="login-layout">
    <div class="main-container">
        <div class="main-content">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="login-container">
                        <div class="center">
                            <h1>
                                <i class="ace-icon fa fa-leaf green"></i>
                                <span class="white" id="id-text2">Quản trị Admin</span>
                            </h1>
                        </div>

                        <div class="space-6"></div>

                        <div class="position-relative">
                            <div id="login-box" class="login-box visible widget-box no-border">
                                <div class="widget-body">
                                    <div class="widget-main">
                                        <h4 class="header blue lighter bigger">
                                            <i class="ace-icon fa fa-coffee green"></i>
                                            Đăng nhập
                                        </h4>

                                        <div class="space-6"></div>

                                        <form>
                                            <fieldset>
                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <input type="text" class="form-control" placeholder="Tài khoản" value="@Model.username" id="txtusername" />
                                                        <i class="ace-icon fa fa-user"></i>
                                                    </span>
                                                </label>

                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <input type="password" class="form-control" placeholder="Mật khẩu" value="@Model.password" id="txtpassword" />
                                                        <i class="ace-icon fa fa-lock"></i>
                                                    </span>
                                                </label>

                                                <div class="space"></div>

                                                <div class="clearfix">
                                                    <label class="inline">
                                                        @{
                                                            if (Model.remmember == true)
                                                            {
                                                                <input type="checkbox" class="ace" id="cbRemember" checked />
                                                            }
                                                            else
                                                            {
                                                                <input type="checkbox" class="ace" id="cbRemember" />
                                                            }
                                                        }
                                                        <span class="lbl"> Nhớ mật khẩu</span>
                                                    </label>

                                                    <button type="button" id="btnlogin" class="width-35 pull-right btn btn-sm btn-primary">
                                                        <i class="ace-icon fa fa-key"></i>
                                                        <span class="bigger-110">Đăng nhập</span>
                                                    </button>
                                                </div>

                                                <div class="space-4"></div>
                                            </fieldset>
                                        </form>

                                        <div class="social-or-login center">
                                            <span class="bigger-110">hoặc đăng nhập sử dụng</span>
                                        </div>

                                        <div class="space-6"></div>

                                        <div class="social-login center">
                                            <a class="btn btn-primary">
                                                <i class="ace-icon fa fa-facebook"></i>
                                            </a>

                                            <a class="btn btn-info">
                                                <i class="ace-icon fa fa-twitter"></i>
                                            </a>

                                            <a class="btn btn-danger">
                                                <i class="ace-icon fa fa-google-plus"></i>
                                            </a>
                                        </div>
                                    </div><!-- /.widget-main -->

                                    <div class="toolbar clearfix">
                                        <div>
                                            <a href="#" data-target="#forgot-box" class="forgot-password-link">
                                                <i class="ace-icon fa fa-arrow-left"></i>
                                                Tôi đã quên mật khẩu
                                            </a>
                                        </div>

                                        <div>
                                            <a href="@Url.Action("Register","Registration")" class="user-signup-link">
                                                Tôi muốn đăng ký
                                                <i class="ace-icon fa fa-arrow-right"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div><!-- /.widget-body -->
                            </div><!-- /.login-box -->

                            <div id="forgot-box" class="forgot-box widget-box no-border">
                                <div class="widget-body">
                                    <div class="widget-main">
                                        

                                        <form>
                                            <fieldset>
                                                <label class="block clearfix">
                                                   <span>Xin lỗi ! Tính năng đang phát triển</span>
                                                </label>

                                                
                                            </fieldset>
                                        </form>
                                    </div><!-- /.widget-main -->

                                    <div class="toolbar center">
                                        <a href="#" data-target="#login-box" class="back-to-login-link">
                                            Quay lại
                                            <i class="ace-icon fa fa-arrow-right"></i>
                                        </a>
                                    </div>
                                </div><!-- /.widget-body -->
                            </div><!-- /.forgot-box -->

                            <div class="toolbar center">
                                <a href="#" data-target="#login-box" class="back-to-login-link">
                                    <i class="ace-icon fa fa-arrow-left"></i>
                                    Quay lại
                                </a>
                            </div>
                        </div><!-- /.widget-body -->
                    </div><!-- /.signup-box -->
                </div><!-- /.position-relative -->

                <div class="navbar-fixed-top align-right">
                    <br />
                    &nbsp;
                    <a id="btn-login-dark" href="#">Dark</a>
                    &nbsp;
                    <span class="blue">/</span>
                    &nbsp;
                    <a id="btn-login-blur" href="#">Blur</a>
                    &nbsp;
                    <span class="blue">/</span>
                    &nbsp;
                    <a id="btn-login-light" href="#">Light</a>
                    &nbsp; &nbsp; &nbsp;
                </div>
            </div>
        </div><!-- /.col -->
    </div><!-- /.row -->
    <!-- basic scripts -->
    <!--[if !IE]> -->
    <script src="~/Content/assets/js/jquery-2.1.4.min.js"></script>

    <!-- <![endif]-->
    <!--[if IE]>
    <script src="~/Content/assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='~/Content/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>

    <!-- inline scripts related to this page -->
    <script src="~/Content/assets/js/mylogin.js"></script>
    <script src="~/Content/assets/javacript-admin/login.js"></script>
</body>
</html>