btl_web/Controllers/HomeAdminController.cs
using Framework.EF;
using Framework.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace btl_web.Controllers
{
    public class HomeAdminController : Controller
    {
        private readonly Model1 db = new Model1();
        // GET: HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Profile()
        {
            var userID = Convert.ToInt16(Session["UserName"].ToString());
            var profile = db.Users.FirstOrDefault(x => x.Id == userID);
            return View(profile);
        }
        [HttpPost]
        public ActionResult UpdateProfile(User model)
        {
            var updateuser = db.Users.First(x => x.Email == model.Email);
            if (updateuser != null)
            {
                updateuser.FullName = model.FullName;
                updateuser.Email = model.Email;
                updateuser.Address = model.Address;
                db.SaveChanges();
                return Json(new JMessage() { Error = false, Title = "Cập nhật thành công!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JMessage() { Error = true, Title = "Không tìm thấy người dùng!" }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Logout()
        {
            return RedirectToAction("Index", "Login");
        }
        [ChildActionOnly]
        public ActionResult _LeftMenu()
        {
            return PartialView();
        }
    }
}

btl_web/Views/HomeAdmin/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
    <div id="background" style="background-color:aliceblue;margin-left:20%;margin-top:5%;width:500px;height:500px">
        <h1 style="margin-left:5%"> Bài Tập Lớn Môn Lập Trình Web</h1>
        <h2 style="margin-left:15%">Đề tài : Quản Lý Thư Viện</h2>
        <h2 style="margin-left:25%">Lớp CNTT4-K58</h2>
        <h3> Giảng viên : Nguyễn Thị Kim Sao</h3>

        <table class="table table-bordered table-hover">
            <tr>
                <th colspan="3" style="text-align:center"> <h3>Thành Viên Trong Nhóm</h3></th>
            </tr>
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Mã Sinh Viên
                </th>
                <th>
                    Tên
                </th>
            </tr>
            <tr>
                <th>
                    1
                </th>
                <th>
                    Mã Sinh Viên
                </th>
                <th>
                    Đỗ Tiến Nam
                </th>
            </tr>
            <tr>
                <th>
                    2
                </th>
                <th>
                    Mã Sinh Viên
                </th>
                <th>
                    Đinh Trọng Hiệp
                </th>
            </tr>
            <tr>
                <th>
                    3
                </th>
                <th>
                    171201330
                </th>
                <th>
                    Trần Hùng Tới
                </th>
            </tr>

        </table>
    </div>   

btl_web/Views/HomeAdmin/Profile.cshtml
@model Framework.EF.User

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<html>
<head>

</head>
<body>
    <h2><marquee>Profile</marquee></h2>
    <table class="table table-hover table-bordered" style="margin-top:5%;width:75%;margin-left:20%">
        <tr>
            <th>
                Tên người dùng
            </th>
            <td>
                <div class="col-md-6">
                    <input class="form-control" value="@Model.FullName" id="txtFullName" placeholder="Tên người dùng" />
                </div>
            </td>
        </tr>
        <tr>
            <th>
                Địa chỉ
            </th>
            <td>
                <div class="col-md-6">
                    <input class="form-control" value="@Model.Email" id="txtEmail" placeholder="Email" />
                </div>
            </td>
        </tr>
        <tr>
            <th>
                Email
            </th>
            <td>

                <div class="col-md-6">
                    <input class="form-control" value="@Model.Address" id="txtAddress" placeholder="Địa chỉ" />
                </div>
            </td>
        </tr>
    </table>
    <div style="margin-left:40%">
        <button class="btn btn-info" id="btnSave" style="width:60px">Lưu</button>
        <a class="btn btn-warning" style="width:60px" href="@Url.Action("Index","HomeAdmin")"> Back</a>
    </div>
</body>
</html>




@section script{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnSave").click(function () {
                const formData = new FormData();
                formData.append('FullName', $('#txtFullName').val());
                formData.append('Email', $('#txtEmail').val());
                formData.append('Address', $('#txtAddress').val());
                postData('POST', '/HomeAdmin/UpdateProfile', formData).then(function (msg) {
                    if (msg.Error == false) {
                        alert(msg.Title);
                        window.location.reload();
                    }
                    else {
                        alert(msg.Title);
                    }
                })
            })
        });
        async function postData(verb, url, data) {
            const response = await fetch(url, {
                method: verb,
                mode: 'cors',
                cache: 'default',
                credentials: 'same-origin',
                redirect: 'follow',
                referrerPolicy: 'no-referrer',
                body: data
            }).catch(error => console.error('Error', error));
            return response.json();
        };
    </script>

}