btl_web/Controllers/TacGiaController.cs
using Framework.EF;
using Framework.Model;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace btl_web.Controllers
{
    public class TacGiaController : Controller
    {
        private readonly Model1 data = new Model1();
        // GET: TacGia
        public ActionResult TacGiaIndex()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ListTacGia()
        {
            var listTacGia = new List<TacGia>();
            var list = data.TacGias.ToList();
            foreach (var item in list)
            {
                var model = new TacGia();
                model.Matacgia = item.Matacgia;
                model.Tentacgia = item.Tentacgia;
                model.Diachi = item.Diachi;
                listTacGia.Add(model);
            }
            return Json(listTacGia, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveChange(TacGia model, int id)
        {
            try
            {
                if (id > 0)
                {
                    var update = data.TacGias.FirstOrDefault(x => x.Matacgia == model.Matacgia);
                    update.Tentacgia = model.Tentacgia;
                    update.Diachi = model.Diachi;

                    data.SaveChanges();
                    return Json(new JMessage() { Error = false, Title = "Cap nhat ban ghi thanh cong !" });
                }
                var checkTacGia = data.TacGias.FirstOrDefault(x => x.Matacgia == model.Matacgia);
                if (checkTacGia != null)
                {
                    return Json(new JMessage() { Error = true, Title = "Bản ghi đã tồn tại !" });
                }
                data.TacGias.Add(model);
                data.SaveChanges();
                return Json(new JMessage() { Error = false, Title = "Thêm mới thành công !" });
            }
            catch
            {
                return Json(new JMessage() { Error = true, Title = "Đã cõ lỗi xảy ra trong quá trình thực hiện !" });
            }
        }
        [HttpDelete]
        public JsonResult Delete(string Matacgia)
        {
            try
            {
                var delete = data.TacGias.FirstOrDefault(x => x.Matacgia == Matacgia);
                if (delete != null)
                {

                    data.TacGias.Remove(delete);
                    data.SaveChanges();
                    return Json(new JMessage { Error = false, Title = "Xoa thanh cong!" });
                }
                else
                {
                    return Json(new JMessage { Error = true, Title = "Khong tim thay ban ghi!" });
                }
            }
            catch
            {
                return Json(new JMessage { Error = true, Title = "Đã cõ lỗi xảy ra trong quá trình thực hiện!" });
            }
        }
        [HttpPost]
        public JsonResult getInfoId(string Matacgia)
        {
            if (Matacgia != null)
            {
                var sach = data.TacGias.FirstOrDefault(x => x.Matacgia == Matacgia);
                return Json(new TacGia() { Matacgia = sach.Matacgia, Tentacgia = sach.Tentacgia, Diachi = sach.Diachi, }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult timkiem(string tuKhoa)
        {
            //Lấy danh sách kho
            IQueryable<TacGia> lst = data.TacGias;
            //Nếu có từ khóa cần tìm kiếm


            if (!String.IsNullOrEmpty(tuKhoa))
            {
                lst = lst.Where(p => p.Matacgia.Contains(tuKhoa) || p.Tentacgia.Contains(tuKhoa) || p.Diachi.Contains(tuKhoa));
            }

            return View(lst.OrderByDescending(p => p.Matacgia));
        }


        public void ToExcel()
        {
            var listTacGia = new List<TacGia>();
            var list = data.TacGias.ToList();
            foreach (var item in list)
            {
                var model = new TacGia();
                model.Matacgia = item.Matacgia;
                model.Tentacgia = item.Tentacgia;
                model.Diachi = item.Diachi;
                listTacGia.Add(model);
            }


            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Communication";
            ws.Cells["B1"].Value = "Com2";

            ws.Cells["A2"].Value = "Report";
            ws.Cells["B2"].Value = "Report2";

            ws.Cells["A3"].Value = "Date";
            ws.Cells["B3"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A6"].Value = "Mã tác giả";
            ws.Cells["B6"].Value = "Tên tác giả";
            ws.Cells["C6"].Value = "Địa Chỉ";


            int rowStart = 7;
            foreach (var item in list)
            {
                if (item.Matacgia.Count() < 5)
                {
                    ws.Row(rowStart).Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    ws.Row(rowStart).Style.Fill.BackgroundColor.SetColor(ColorTranslator.FromHtml(string.Format("pink")));

                }

                ws.Cells[string.Format("A{0}", rowStart)].Value = item.Matacgia;
                ws.Cells[string.Format("B{0}", rowStart)].Value = item.Tentacgia;
                ws.Cells[string.Format("C{0}", rowStart)].Value = item.Diachi;

                rowStart++;
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "ExcelReport.xlsx");
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();

        }
    }
}

btl_web/Views/TacGia/TacGiaIndex.cshtml
@{
    ViewBag.Title = "TacGiaIndex";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link rel="stylesheet" href="~/Content/alert.css" />
<link rel="stylesheet" href="~/Content/assets/css/font-awesome.min.css" />
<div class="main-content">
    <div class="main-content-inner">
        <div class="row text-right">
            <button class="btn btn-info" id="btnadd" data-target="#myModal" data-toggle="modal">Thêm mới</button>
        </div>
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">Tables</a>
                </li>
                <li class="active">Simple &amp; Dynamic</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                @using (Html.BeginForm("timkiem", "TacGia", FormMethod.Post))
                {
                    <div class="input-group mb-3">
                        @Html.TextBox("tuKhoa", null, new { @class = "form-control", @style = "width : 200px" })
                        <input type="submit" value="Tìm kiếm" style="height:35px" class="btn btn-info" />
                    </div>

                }
            </div><!-- /.nav-search -->
        </div>
        <div class="page-content">
            <!-- PAGE CONTENT BEGINS -->
            <div class="col-sm-12">
                <table id="simple-table" class="table  table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="center">
                                <label class="pos-rel">
                                    <input type="checkbox" class="ace" />
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th>Ma tac gia</th>
                            <th>Tên tac gia</th>
                            <th>Dia chi</th>
                            <th>Xử lý</th>
                        </tr>
                    </thead>

                    <tbody id="table"></tbody>
                </table>
            </div><!-- /.span -->
            <div class="col-md-12" style="text-align:right">
                <a href="@Url.Action("ToExcel","TacGia")" class="btn btn-default"><i class="fa fa-save" aria-hidden="true"></i> Export Excel</a>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="width:75%; margin: 0 auto;">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <i class="fa fa-home"></i>  Thông tin tác giả
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body validate-form">
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Mã tác giả</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập mã tác giả">
                            <input type="text" class="form-control" placeholder="Mã tác giả" id="txtMaTacGia" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Tên tác giả</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập tên tác giả">
                            <input type="text" class="form-control" placeholder="Tên tác giả" id="txtTenTacGia" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <label for="maduan" class="col-sm-3 text-right"><strong>Địa chỉ</strong><span style="color:red;">*</span></label>
                    <div class="col-md-9 text-left">
                        <div class="input-group validate-input" data-validate="Bạn cần nhập địa chỉ">
                            <input type="text" class="form-control" placeholder="Địa chỉ" id="txtDiaChi" />
                            <span class="focus-input100"></span>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="name" id="txtId" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Thoát
                </button>
                <button type="button" class="btn btn-info" id="btnsave">Lưu <i class="fa fa-download"></i></button>
            </div>
        </div>
    </div>
</div>
@section script{
  <script src="~/Content/assets/javacript-admin/TacGia.js"></script>
}

btl_web/Views/TacGia/timkiem.cshtml
@model IEnumerable<Framework.EF.TacGia>


@{
    ViewBag.Title = "Tac Gia";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">Tables</a>
                </li>
                <li class="active">Simple &amp; Dynamic</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">

                @using (Html.BeginForm("timkiem", "TacGia", FormMethod.Post))
                {
                    <div class="input-group mb-3">
                        @Html.TextBox("tuKhoa", null, new { @class = "form-control", @style = "width : 200px" })
                        <input type="submit" value="Tìm kiếm" style="height:35px" class="btn btn-info" />
                    </div>

                }

            </div><!-- /.nav-search -->

        </div>
        <div class="page-content">
            <!-- PAGE CONTENT BEGINS -->
            <div class="container-fluid">
                <div class="col-sm-12">
                    <table id="simple-table" class="table  table-bordered table-hover">
                        <thead>
                            <tr>

                                <th>Mã Tác Giả</th>
                                <th>Tên Tác Giả</th>
                                <th>Địa Chỉ</th>

                            </tr>

                        </thead>
                        <tbody id="table">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Matacgia)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Tentacgia)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => item.Diachi)
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!-- /.span -->
                <div class="col-md-12" style="text-align:right">
                    <a href="@Url.Action("TacGiaIndex","TacGia")" class="btn btn-success">Back</a>
                </div>
                <!-- PAGE CONTENT ENDS -->
            </div>
        </div>
    </div>
</div>